import { Button } from "std-widgets.slint";
export component MainWindow inherits Window {
    width: 300px;
    height: 200px;
    in-out property<string> result-text: "点击下方按钮测试您的设备是否能够正常运行RTL启动器";
    VerticalLayout {
        spacing: 10px;
        alignment: space-around;
    Text {
        text: "感谢您参与RTL启动器兼容测试";
        stroke-width: 2px;
        stroke: #3586f4;
        stroke-style: center;
        font-size: 20px;
        color: white;
    }
    Text {
        text: result-text;
        color: black;
        font-size: 10px;
    }
     button := Button {
        text: "点击开始测试";
        width: 100px;
        height: 40px;
        clicked => {
            on-button-clicked();
        }
    }
    }
    // 导出回调接口供Rust使用
    callback on-button-clicked();
    callback set-result-text(string);
}